#!/usr/bin/python
# vim: set fileencoding=utf-8 :
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzs=open
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzI=True
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzsI=len
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzsF=dir
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzIs=reload
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzIF=False
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzFs=map
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzFI=int
import base64,imp,os,sys,StringIO,zlib
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsFI=os.path
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszFI=base64.b64decode
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLszF=StringIO.StringIO
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLszI=sys.modules
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsIF=base64.decodestring
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsFz=sys.path
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsF=zlib.decompress
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsIz=imp.new_module
__FILES={}
__os_path_exists=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsFI.exists
__os_path_getsize=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsFI.getsize
__builtin_open=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzs
def __comb_open(filename,*args,**kwargs):
 if filename in __FILES:
  return rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLszF(__FILES[filename])
 else:
  return __builtin_open(filename,*args,**kwargs)
def __comb_exists(filename,*args,**kwargs):
 if filename in __FILES:
  return rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzI
 else:
  return __os_path_exists(filename,*args,**kwargs)
def __comb_getsize(filename,*args,**kwargs):
 if filename in __FILES:
  return rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzsI(__FILES[filename])
 else:
  return __os_path_getsize(filename,*args,**kwargs)
if 'b64decode' in rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzsF(base64):
 __b64d=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszFI
else:
 __b64d=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsIF
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzs=__comb_open
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsFI.exists=__comb_exists
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsFI.getsize=__comb_getsize
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsFz[0:0]=['.SELF/']
__FILES[".SELF/__init__.py"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsF(__b64d("""eNrjUk61NDA0NbUwSTVLNDFJMjSxtLBIMzRONTKytEhKTkqz5OLiUralDChzKSv4J6WVFicnlqSmKCR
VKvhXVBZVKgRUlmTk58Gl8osUNDJKSgqs9PULKvOT9PJBivSS83M1FZSp4AYAa3A+fg==
"""))
m=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLszI["__init__"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsIz("__init__")
m.__file__="__init__.py"
m.rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzs=__comb_open
exec(__FILES[".SELF/__init__.py"],m.__dict__)
__FILES[".SELF/JHOpen.py"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsF(__b64d("""eNqtlN2OmzAQhe/9FCPQSuSGgCEEkCKt1JuqqsS+AeLHJF4BRthVl3362kDcpAHUqpkoSmKf+RgfT4Y
2HesFnD9pBxmHJEkcGYkzfso3mDVtSYwRnYSMzzIlmUTy21XmoaLOOIdvX5OOtGCx/J0UAnbxtB0gkF
GSCtKUtlSkKViKMWEmpKPVx1GtolPMaTEcF1+5yAQtGiIurJx3XEfTe5KV3+UaV/hEFzs+SeNdV/NpB
Y86m7Ql/0nFBSzDPn8aOg/rvJvcezfsLpN5NvmgXGwX4d3BVFSsh1GlSONLmULbhbux2ejyBt5/wOua
/3yCzUUvm8DSuYfFXBUDJXW5hZgJwR2B1JzAFX58gHc9bYX0+k1ZRzm0TMBkYAwv3HhZOOXMCtFygfN
2hJYqwM4TrxG7DyWMnbN6P/N/aOr92URdGV40fqsvVkDe6g3+VQdgfzX/H7oAH1a7AAfP6wJ83OwCHC
Kqxk6bNUSOndPJSNMmo22aGnMx3uSWsln9Vs5ex9jOvpkoxpd47wYHbNfsfDsXvN9uzYcYMdqNHTJJ5
LiHQ+iTIPP93PWjMKxcj2AchXmRVxFCyDz9X5jIhCSvfvAiE6SEfIDkY+gHeBvkqGz1ljykdRGii/f7
bmC5zZTILlizA/MJNfwC1/WekQ==
"""))
m=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLszI["JHOpen"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsIz("JHOpen")
m.__file__="JHOpen.py"
m.rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzs=__comb_open
exec(__FILES[".SELF/JHOpen.py"],m.__dict__)
__FILES[".SELF/LogStore.py"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsF(__b64d("""eNqtVE2PmzAUvPMrnhKtRKQNAUKyECmrnnqqSqUeowjxYRJvACPsqEur/vfaYDubQNqVtj4AsoeZee8
N4LImDQNCIaYQ2t3it1AsO4RpgSu0cQ3cw1gTpyiJ05NCC1R3EXeJXhppEVMKX8jhOyMNApMkLyhlMN
v0gJUBfJEzi3JcINj++t3vr7v9DOUQRbjCLIrAVCKdjniGR/nY7dpy6y1KLHgsScapJz8mStXv2MUac
loRN3vA1YELvp991hMHHfEnymKG0xKxI8lkJxznUtFFQPD3dJ1GV5FyIhs/Yt9x3/gP5ZykJw5cTKwX
gqsxeovWBWZgcsxst5k7sJfGnaWmxDlUhI0EwKpjdgQLvWLKqGC/ldb+PE2menzDRFvKUMl9lKcMNzC
v4YFOHkYYJeHqUnAo299PQhSsw2XpHO2Gpe95XSNI64DY6CC+koqPFRUUAanRaDevRu+stccxGYoYn3
18Lti9sd+UpWifNG3d4IrB8/MQO5Ia+bZ/N5CurQOZ8y+MHlEGJqY/cQ3bz7EoW43TdbSFnDRyAkpJf
AI8a2Mln1DLY6JZ3KtQsKYFdbK8OrnTwd1Qd2+lBeFGTdkr1xsQ8aH3NSmt1QDyr4gexOvzvE/owIOS
Xl/xotcU1UyLPg1E+1maw/+m1Z1EnICXpcj9u60LBswZKt7bPvmPtv9ifel8zPrSNYwpCmxntfI9tI4
9L3G8wPdzZ4lcN/CTNMkDg2O2H1tTYwphkp9pGjMe5KSF8LXlffrW8shX+ojH1zwyVm8Wi7oliUUEyE
pJOYPpf/DwB8Ey7lk=
"""))
m=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLszI["LogStore"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsIz("LogStore")
m.__file__="LogStore.py"
m.rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzs=__comb_open
exec(__FILES[".SELF/LogStore.py"],m.__dict__)
__FILES[".SELF/Decipher.py"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsF(__b64d("""eNqtU9lum0AUfecrrrCqYNUiA8Z4kXjwElVqlbhNVFVqHCGWwR5iAxrGcZD68Z1hADsQ5aUdLIPNuee
ecxdyyFLKwPdybFvg5bBG/OKH3+QdenuS4JmpRDQ9wJIWGUtBX5JshykQGT6/eShjeQyqY9E5dqhUOI
plCkldIgW0gllKsPfyHFY4kOxa6sc4YNCfScBYAX5CHIHrkoQw1wWtTCVpyqSoQU9LtDhdjE5ewFFXq
7n95et2vPhZ3Mb3haXKQAN9FHlIQwxO14MepIeM7DFoVNU2pz+bX/3Par9iNBrlIZalI8lWiJfxzRcM
Ln6jMgkMnnHxwCg4d2mCG3fG8CxyXTVNFh0hbk3V45QkoD2q8c5Va4qnPomgesb7HIO6iOPdc1y8bnM
TGTYa1SUYXbJLs7UuYb49I7pvWyEORGm0roO6CnZLsiypLJ/THR49wSdB13Y3eAd6u17duMvFkr/s1F
Q0u5YwvpCApAaEZHeFhLYqnZsSE1/KaJWhppx8TNn+S6c5oyQDTd0gS203pIt/5K2Gp2oJjSYXxexIk
3fwFdJUiFiTxDtgviaOo7ruwSOJ66rVAJmyxQznzG02zjnvXmXPlE3zwHmL1N8M8tUxv3v5gYzh/Qj/
Plp0Hn0Lc//0abjin6uaaqwoPTxFxmg0sbDtWZZvWNPJJDKG2DSnEz/wo6nCMc6/nZ7Sg7UfHfPAYzg
Ev4D1a0EL+F6wXZo0r1JucsdYNru+zorU11MBElvch95/0PAXEOVzvw==
"""))
m=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLszI["Decipher"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsIz("Decipher")
m.__file__="Decipher.py"
m.rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzs=__comb_open
exec(__FILES[".SELF/Decipher.py"],m.__dict__)
__FILES[".SELF/TransformRule.py"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsF(__b64d("""eNqtWG2PmzgQ/p5f4Xq1arjLUvMashIfquuuundtOXX3dDpFUUSCt8uWAAKSbbTqfz+/EsCUpC9IicC
eeTwzfsYeO97kWVGBKt5gEJYgQAiRXxAg9hYE4CyJU3xpjNZJWJbgrgjT8j4rNh+3CQbjbPWI1xXQLr
mUNQLkifA9WC7jNK6WSzCmUAH7Qxy3lnaYNH1UGf0BhxHw4eNDtIRc3B0ST7InXCw/430J/DmE+mMWp
2A8/xbwJGAt0lXyAwuNuAXUdoIzhymu7vY5hhO4DclfVsLFgls1HbKqwGm4wcKsKCaRGs/HJ1nXmAFq
D5gTAxfa5Md0Daor3Ot2UvfGMMnWYRVnKfGtwJ/oi0ZUxNRbQy6us82KSMnQn+Qd4hawKNOe7/FO1W1
4p3Ry7/LwE/5AJoJ4h3c4rW4i6p7wzqk5G+Z5sue8FmGSo5PxJ5wO7I8bV/PYaHBA0dOjIny6xWVJgs
px2yATWPJOKMPtDaGFUfSWBqIHSerPBq3J3tFMGdA30bD+R8bpIQBjGOAPzpghBPNICO7KIe0DXwtcb
YsUqKJC0q7n/hCXoClNOSRnHkkEVM+8eViTBP+Q0OQWU/6pgM3FSgIdKESf+L4HK80qhqdYIzG8FgZ9
1llaxekWS39nLQkVaa6OuvBPE+NOgbGYBAs1QnugDE/LQDyouQ6L/8NeYrZjG9RrFn/lsegCtpZciWS
13VaG1EtcEUvDbVL1GdnCnKuGLHq86BPT6LT2uqGo46TE4EOWypmzbIUfpwHJEDgKNyKcgNPsFhBuY0
bbOSz16YdMl+Cwhx6m1Ouki9yNhHxN7xZge4uRUB0qH5D4A3wVne4UXNtGarop0mRPqtOt6Y2wwDaUk
HKcjvi8H3ohYUwF5pCbbRzFR5mbpwwnRrP6efC9MI2Fs7O9CeKIKoMneAOYESSQ27vYrmuC2G4354M6
HdnKQyYkictKLNMtWP0T5u0d7MnzV01n1Blr9ThTZUXogLVWBMWMHq/m6siLuaq5YKn7o8phGv2E9gs
fptskgWxxgbLesA+Z1GvbUFxlId9OJ7myHLdSqBuHEqxZ3tQ7ZoNJzdUZTPCXtSw8F7UxVndPDuSgTK
/DoRZglyeO3bMtq3C1GVLNObYTO+5xYL2swqIqn+LqoS8evCCuLZ0eHdJTOd92vsn5Rin+jZEnqsWkh
Fdh5z1yxLUizkmgieMVOVfR8TTf56+nQWiMxSfKigjM+ml6VF+cP1GTpnUJGtQpJmpFuX+K6kHOkNss
ag8iPBP8drzboCLeMMvvyCkdSndca6Twp4l5qBc7FkmD2uQWtbLoc1oVuIDkIeFbaxtyrg6/IGVTnoR
rOrmX5OQFtUbDRbcBdBt+Zw3CGrfpaYLTRt1RW6W98A279m3arXQ7Bg+Q/UjwJ0geNFxvIICtU9gJ0f
JVj8QFAxr9QjeqkroQp7zQ7Vz16JvP7B6or4tkbC47u4ZO4Pl/55vz6Pzt+fvzW6hpvxmskhdxmhqjm
N4IsSJ6CXwfLpebME6XSyima8qpGPO7qMeS1BLsLqreMoS7QtppSq+zfC9vrkQlK2pZIS3q1rAKga9C
knNLGJFcfvny5TOkQnQRgpcAGsb19ZVhTl1kTz3TsWYm8t68Rq5jGJaBpm/gBNDLICL5DqfZLgN/Web
acmnzrmAAOqIf4bZ6oJ/0cgXAfEXf/yUbebZ9jEPaVEaflztcsDsArsb05LXAJXiuby1IN9vBSfcmzM
kn/SIfhJzCanrVAXkLpStpMZHhXiDvAhnAcMleS06BVIBQABe7MGFD0gZ5xUXNu7m+YcbKexPS9pQVU
ZHFkR6uq3gXV/tS/4h3MX56T2YSfiXS9R0SkUY6miDuf5yzIUxbdx3dcC3dQCxI2xIXZNOknZ7rOaaN
TAOZFpFg9pe043XKxgREUWdG5tvyIWZx+Ofm9uoDn543HjKv6+m5+XN2Nb29gl/JjEoC8tWgwiXxGfi
dO0wpxDOWkURhP2e+kPRQzahltcmBz7gl+vgqnxcixRS6RdtNTugmbNEbd04MRZNJ41ltoG+ZdBHK5c
izR6MzPEOG43g2dkPbXhn2zPPuDQub5sxbrVf3sxGR8X/uORudgWB1vy3JdOMIrPYg+LIv9uDvffVAE
ld2kdpr/FBV+eWrV/k+W+kZFaJnOQ2c/QIb/gdiU+lW
"""))
m=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLszI["TransformRule"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsIz("TransformRule")
m.__file__="TransformRule.py"
m.rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzs=__comb_open
exec(__FILES[".SELF/TransformRule.py"],m.__dict__)
__FILES[".SELF/Transform.py"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsF(__b64d("""eNqtWmlzo9iS/V6/QuGOnu4eV7vYl35RH0CA2ITYhJB6OirYxY7Y4dcP2LJdS783b2JGVkgI8mbmzXv
yZF5wWJf5hgm8uLoG9SbOq7Ju3387zeYALH/Pb+Dlvfkpi4vgD+jDXThpyuJZcL18ODzLr4KHuyD8Kt
jVWRa7r6Lr6y58eBVFXkXr4MU08GzxTfQuhn4IV6/N2imasKxzvcuCV9e/Pflq69mv+9ddCfbBy5yme
R+w+bV0k8BrN7/98SJBfNgsLz8IN1++xEXcfvmy+fVF0Us4Xjx/lQaBZ/H19aPQk/8a0c8/xvPX3+4a
wH+loXJqJ2++rJ467arm+9g8eWVexcukf+2K2Cv95aB++K8/n/7zr4ffXi1A/8pCvUbs84/xevMPfgt
I+x6014m8DgE2H19n9zzN9eM9SOi7Az8Iff4RFk9dcevKNvhSZV2z2PpR8RrZ57k+dG1IPLy6in1lB3
iN1ZudH9Q8NVUWt4uSj28a8K9CBbxG4+XzOfrfKf0T2Px1H0l8M/JdZpH/25Hw20jybeSCzGBB80NVN
u1DXPyNpqesHBY8/frbx1/ipijbjXowzI3OakfWMH+55+jXmPwqtId/Ngnk1RXoHYtxuHn4jxf0fb67
8p2m++JC7+i6B/4lbsAdYiswXiL/iq33Nf9K29ta/MfrWkDw94oPh7fVO9yj+p2tNy2O631++O1PcPP
XU9PWcfUGZwj5Vuvhdew3q/ytu29aX+Pxt4rR79x9V/Ds4sukv82Zpy9O117lMlpB/v30Pv7o26sp7G
/n8Jrbi6lfyuIVDO+IDrImeFs14t/x9l+n5T9fw3uE/kmaQuT/7H4Y3v2H38G8MM/mNT5vRLq5Y/O7w
H7Lm09hXPhOlr1yydcTfSUpGPw3IvKd7fvIbzPArQMnfb0E/5vef1NBlyR3/OZfOvsjir/V++cvK7J+
+evzj9G9a0D/Rw1xdR//LQ3ex3+LwSkOMv/vFuK5vDw5VZVNz7X51x8t3WEB4++V9z0tXsSBt+L5Sic
H4C3510y5M/vrZN8DRX5deu7ZdA/2uqLfa38v2cvR9vkoLl7T8xujd6+R78j21YP1/b8y8MMUPv7o8K
vNd6jWQdvVxd+Yvksu/drayBROHiyNzOfPD1++5E5cfPnycA8Q8hL1NmjaoP7y3hZ9/qpDejX7whnr8
ZKiv/wCEvATBENPII4+wZvfl78/YfDT3pk+QQCI/QFgSyVauGrzCBAA8Nfm4blUfVqg0LTOU9JseNNU
P4FP4MMGWuJ559afUfpnnP4ZgnynddqpCpbDn2Fq+QRBjmNBCMcABCcgFCYhgGAoAENBEAYBnFkFoe3
yWTZvY6jCr8vYf0SeoCfoTaBy3wROTuGXXRI77xe75hr7bwJHwWCVF6sMAUDcm1VBJFncYN/GNUHTxG
VxH/g8haAPilZ411V0WfYmHxdLwHsn+/uruVO9XHg5u54qgtb8Oh4ngRPe51yZcf5+bV2A3wHwd4h8B
ODlFICsH+DX4l+riov36TtRoDhfqXp1aw3wKtA5b5f6uG47J3vMHe+6gOJNR7d0MWkwvclhsOP6OIGE
GEyGIf4m19fvi/sE3I2gzAYkNg+/P2weGCfr43SBCPa09KNyXHTjPzbHf2zuq7p5XtV/bO5ubO5ubOg
uzvxPIqPBJPvbw+b3Bap3AJPfARhCnjD0CcTgJxDAXhAMke8IBvElgZZR/yaC154D8F2ztjGHoNXTDt
hdtSnCnOhnmFner+3U4fozxDV4O6CIhtWDa7IUJI/HmVrWh0t+hmh5+Z45Jy4PTATczjYqi3or88vZs
A+VNkpQyAQfk2pZEVrwGuA6+QXY8gWL7F3evw2Dz1NzmWbXQ0+ZpHHCGAHVdE61KXI8Dq0FourwiC2D
FQhXA2ZPymR7uF6WE4t1TrIUFBqOY4UL/i0BjkHTCb4SVsS2r8R1VMLHfg/HkoA8Lp7SR8Qdb+kJJvk
5v0Q2iZ12cElbF6eXTtk+TIxlDHeGIlZbvmHTbstlkDUU2x0bn9eZ+o8nGjVbTsKPxMgvwKAHcWfH6X
LNNIWgOUS9zHDW6CeOEyILGOklwen2OtwgFDQ6EzMXScHuHv0UWk1V6DbNB8DR5UvBKim+x3LMb4JqK
51CYD/D/UU5ls1eLg4x1jsCuowZbR9KtMdFbS/c9hCT+J5GDXt8B5PzyI83r8frfkaqkutzLmooxOdn
ZOw6jwARd3tYfOIwf2c+houGbNgyLbwtDf3i7iZ6i0seEnW1Q3eKCNINDMhMtuMJTWfWtV4D6JvwWQ5
gJhYg9bEqL3bUXY4AVC/kQue4zBbO/ga6NXg6z7aOMtv2dK4R36Ah41yMV+NKDr7PqJNPX+lHNz8n14
U7OCNrhi4FztXNagl9mI7LuVacJlKkiL3rJzl2RVQtccXFyEgKxzA3LHU3G9Wje9srVcWe6/5EIbxwX
heEBumu22X5cmw8YxRBegoKjlIdIQVYl1w9hRKXnOkw7y3lEb7BPqWbyE2Ii5CtM+EoJbsTIdoHUuPV
HsIzh+PPQcadGlU4BWTDn/JOqUJJ1PhHQydH/zpqIh1TK+grvtZyz9nWjDjOLpo0pwumJdEIrCs3DEi
GuCsAUk+QG9cZtMW+soJnxbK2OgypNzSzKBuGAiujz/qJtzBNlYuzxecEHnaYbJ3rrvbG+ZgxZ0PXVx
QFj5kE6vyCEYvWUIa86sqwnM9kGOvHG87R4XAk+17OsLrVcF6PNBcXLZZRG50Z0eL8mFwPIpEoAQGVP
h5lSLpvmfws2WPVZ+LF7QHUBNSoIntavuyk4rAGNYP2VZ1M8MX9X5Dg8vePza4so6W9UoJx6c2Rhcme
zy/flCpsQHI5wDFiBCECuPOjZB4JRP2GH1Hge35ciBHEnlDgCUKIj79//BOEPhlBdWdH7A8EXjjyzo4
f7+wYl8337PhxYcaF/1q+jHvH0+LMhvstDuh6kpjaN9y4HJ3ia0H6PHahpASHhIGmbctRK+YABHBmSQ
2mXMct7JnzBfOndEsDnq/3QZpKgnilW+i4PS6Fh76Ve7SKFzYkGd7n2jN/xS2FFU0OAQ/KeDABCeKsP
BUjbo65U0cgON4IM9p1jIGxyK3djrtqbrjhOvuuJ4rVAe0YCzY9zDySO586rymgY5acTdIJPfA8ALbR
fggEuKfzc+SmNE9l1dlRd4gcE6G9AOe644K0CI1W2BvLT564jTbId9mxAtVbPhZRogyQ6F331J4/Rot
EKbgE3dm1nYoLrXABMDSGgeFmQrFs0dphJ6VeI7awFi15QIM4nUQAyLNY41y4k7e32UG0jJXkDVKO2W
B7JfKQ96jZBLTBqTMdTbmGXdl0WjoUjhb7dCVotYE07CTvtAE9E6yrYnsahtdMsm1sJe7kAveEck7kd
s3MWokMQZ9EYvkBWi85lwIc4jbZDRKVSuh6y6Fh0d8ip9XJmkRNFJYlQt5D5XGbqpdSJc993RwFNRDB
BtFrYU6iY4EWlGPt7WvgLcNsa35hStWjF5K8wqMBu3i8nDhMF2UNbnfR+p2hoBFYneX8shZQlIJP9ei
cmlZiLSGioyKxohIycIWvFY/cHcybzz0reX5zyTSIDHOcm6MN7BrzciZ04lLGyt5OD13XLULnNOPAPG
j7AOUuKlAjQ0q7h9bBeMmVezTfJmrgklFShHu+3LO6gGjkNi6VtdpH8YnLg4nYVgmYcTV3MAtjvji7c
cZ2SMfvjdi+gQd6n/h9RQnqOUiAnW66xNKY0bNkOVgIulQNZkJVgY7Zjr0f43hFQtp4moCVBttlCWiS
BG720hRyzrVIk94lSXL5oUnXNMeO81GujPHQYBWiXYyzM1SEoyPCEdbxg5AbrW2sFNTW0rFzb/yE2Jg
XXwrDczF4xKyFvpvQGs0aAfe2USjMoYlxNHTnMcsUszov2N27lyYgREDyikIGBU9Uhyu8syofBT1uLT
+oq+KuX6TDeFaIRAM1S27IDLrqlKePF5Lt13aA3xGXi2/BfQQ06VLZ6f3aNsQ56ufaqRBRrTIWXXQXi
ONBEfdpo4XpTk9FrkDM8hRSrig5qnKzLyDUt7IchcCQRFPOlp5J32LlMmqQMlo5BVAL3KSGMZ0I7rNI
ZqAZ7Fu02O1tSaKsBVW0GO4wuW8BlT0Jh7M55nHt2PaYUlR86GNPrW3nFEt873FrBlWAgSxf1J6bux2
KASDT7lV8pwmlyvZLj0u7a63HsW2n3iyDa2sYUqQugXHEPfu12h6nrnTFM+HOp/IgRfEQcg0XXC9t7X
kvKC2mpN4NONu4g1BH4JXmrQvPQroLD5knX3JM2Lq8hLhqUpLcEAsGE6vlvh8Xr7ZbAptXnhCGLcUeD
fBcNn5DHSZuDi3txtBjD0cgWMRyDMbXaDK2QU+50loJC4FD5i71hwsPjNml7WZ9Vhbg0TYl6TzK24Q1
w9zaGXiVSo/7IecMyz6vDp8dyfCphDgYCuuxbAUdmnRErTUj8FxJr3quial1PfZex0ZqXOlHZs8Oia/
rPXSJKyc16BiSFPQUht0VS0Jyf6uPIJiLNwromiNqZSvq88zUo+nKVYdn4o/jSAuJgyvEL3x0G1WDnm
dUJO3zJepMF0tvzy2onV+m436F2K1PQGpN8bjTCHJdzIY1AlzxILhNsgQwKvpgYecJOiLiuVihgTENb
Y7peQQuk3e45RHWbqm0mCpCdJFogSx9NRUAX3MyV/h5IUdYOAht0rrHcdpOkk1lsSxPmY8ruh5CDaYt
BO7E8i1VBK3p8yaQIjmfertDL96VDVwfqSYI6TTJDxE7tOYdGsHDdeKI/Une09ItJSdQHUIwtzkdcYK
jvpfSxjsj6dLm7QMZqA5iccC9gVRK8xa4oQ/OwWTi67JNtp6amCUJYcWmo7qPDnxUecIWTwQZT9GBI/
ITDwl9xuh7z44uwCjbquPKVYVBU0NkjaUobiZL29YixaVHok80NBi7uYMaCIBjxgpydHsJyZg1gQMjg
31q+MX1HDCueNBoRLw87wIQzcfXqofUpc96eTyBLkLV0PEaXvMApMh1xWgUSgL8yhpxxcGI43EaWuIp
UUUwHZEWFtEnKbLqzsxasSgIeUDA1DhgJCvo4W7iz1FZJWvtVdd+fW0eE+lo1iO2R72QKAuJu5J7E6s
InriyGE1exhJLva6UUfKMR8HZTIWguFV0KgW70xFsB848wrhqw4pq6siWw2IbaUUQ1WWerAj9JkcTf2
o8Fz164Jq9i0G7FMlUPPDmZSU1x6/xnlu2JzvlaIvxoCvVtJaiST7nR7FxWQQC5o7ZEgECISiqmRqTz
mFCtPA6XErpTmcIW0apEtWCdbOwzmmHW2c1LqD4WlZCfIWBJGVVxQBdb7cms8jV6NLP4muxrqkhnhW3
VwuM4/gs6oBmXhDk7pupokzjImN70Gmxqr2E8qhVNUlePEnlpDzTCje1C6MMo9ZfsrPXGSA4M5jlWNR
Zbz095c637RppjKr6hfW4XLvRwUUX+AXHVLhW3WndzubZNcAKGTkx5V4vIU2RKk/ule1oC6GM2Rd9Kw
1Lu88aFG3rMyrRvlOhUnAkb3CPQOee3yIAbsNBys5TKykqDsMTOau7cGKpfC2EdEgQp5Retox1bY0zf
5m3Vph5aWJzt2TF3U1KHH67T2LXadyWPFUZImSCOcS4SyniblfMp9A8k8px15d7TWPtU8C27NIN1fmh
xi7bYEboGmxCuqi9fcaEaw+F7oy1Jsu4viWLETmEWCocQGlKbmMzXEUSkJBaNgZk9rFrbRtgj9oJC+Y
mA2TAykxsQmL97Oyzpak8G4eTsW+fKcc4APsdDx0jkCMzs9eCpGBD0W1NvVwp3vV77Vam6ditHYDdwO
CpIuvnOiboGrCQNKsc2ssUI4kHZtruNrAwnXctuF3atS3DwDaLsKpXKOTF0gCX8gO7ppaJ0ATrXy+Im
JI7FkuheuWMpSWknZNQnRV7p/OdcSyf716MxexXKONfITEpRVTIBhW9HbX2qN88qumd3VZUAs6Tk8aa
s1gwp7QKxtSIY3ZtIP3hWlwd3Qb9w7LbZHZwXA2StkMYXk5U0TSa3drOAoPpmRM+cqe1xORan82YbdV
Vqxy1EWJVJ0dFiM15Vk0XiByJvmLwnk0DM/C4fYSyxxke6/ZautAamom8DkiN8eltf3F5cE2/nh2rVp
OOCXHLqrQggxq9rZvgrvK2QCZd6xNhTtU0hkyixKdrDDBeEsnk7Qzip3EHENqyNXcT5Zpb2cyiENhhU
0RcFdMb5PWOTREoa13wgUN4wcNDqAWqr/LDfncab+c9sF3LdVl4wda1RmBSSL653PaDLrHKzdqN9pEf
jljmmCqE4GkpHhKzv2LL3lkokBXPcJXd4D0UbLdCuQOgmEWuQjg45lKv+Ss5TCLGbUGJkigH5HICQvp
w7zntRZ934/GYiGingQtcAfdkW71G7hQo9dssrjATrG0Ii6Ap4XM3l1cMxPx6K6Z1GWxwgrzBGH2HFW
w/9d32DEzrntwVImvsjTmy1htFO2M+nwKlyNZbPEmC10rZ9nl6hKgMSk4zShq0M0dbnqozQoo6KkFmq
s0JxONreQ4PO3tU1ANqUgV9Y6bbhPrcsBPhAj5uR4MEw6kvkSJXguGiL500FY2kAUYUJkpL92hrAMXU
0zbe73l4q6OR1ccMc9X3416PdXVrnHk8nE28xPeDB6jBoEkuSSC1Z5KGcjaLg16gQmmo2iTlCiBnXYS
t7AIv/VjIUpPFd7BXWkzXj/htvJ2iG2HUSgD5VCUQ7KB1zqSCMSgmVmIKIsvTBjnbx6yWDCNca5EBNa
oWKWvXkMst36wNiJmPwl6MZDbgutzgelThWkt0LUpXGKJVq8xaOuTriBWxsu7ytDZxt2XF3QiP0MELp
+IOXgV5Nuu+vjae6v5U4e0Ya1oygodSxJyzszY6Ne5ZYMuJwsCeSb/fnVJmsLY4hfP91p6EvmfiYt2N
cjCJcy0STE3IJTrjzH4mZ4QLmSR8yc/Z5dQs28JTnfOlExsj1LTVejNNVRxHp+hBC/ZJuN61c8etX5g
gfd3ewlK6imKzPUxNHZJRW3GdW9qwfGqAC5HqjJuwTqro4eol2kTbPFVmZ9rXqqQX6g7z5w7poW3eGM
mV0ZZ1rgGFdk04rS9j4XEjM3gXNvBtKLApumTFBNmijbhL2gVAXBwV2NJqFzEpXkOIWXZ156JXRSNpo
hLYbW+0MFGMl0sFPgKVYVO3Ww/CcmVn7Aw68twX7MxL6rzunmOOo68WGjDATquv+nqDtCKChW9t87Ld
DVOEKEc+M/zkxETAiZYOspS6eTucsN4/ZwHrZvS5MIn8FpjH7giZEmBh664t9wwZ6uxc0OHIFnSe7TJ
JRMsWtmyPbaAbf0DChX2WCAy+YYaAcKsNaOcs5oGLqB6cjFJ25bzGzqSXDlJ2t89Ii7tex0EZ0xAOmT
TQREopOalaqNviCThyNzrcfVxvZoPEx4ffHz4+0PGt+wRDCAButpwStENZp59wlHiCn0B0wzj1EBefQ
HS9O/Ww3rB6v5n08pBqfewZt0G+Pun84SHT01f/UfJ81+n1sR36/ty0quNifaYcrK+Hj8+6fvvwU0AC
IIoSSIA5COKCCEkQIQgHEEQSrueG5IcPH376/H97/fThp83BDbtmIcjA37jT5jBO9bRRp6V6FG+Xlgn
+em3b6o9Pn6qpdJ/KVWj9t5zfNj/9P/jw3zjMP1A=
"""))
m=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLszI["Transform"]=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsIz("Transform")
m.__file__="Transform.py"
m.rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzs=__comb_open
exec(__FILES[".SELF/Transform.py"],m.__dict__)
from Transform import Transform as O0OO0O0O0OO0O0000 
import time as OOOOOO000OO0OO0O0 
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsz=OOOOOO000OO0OO0O0.strftime
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIFz=OOOOOO000OO0OO0O0.time
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIFs=OOOOOO000OO0OO0O0.localtime
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIzF=OOOOOO000OO0OO0O0.strptime
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIzs=OOOOOO000OO0OO0O0.mktime
from LogStore import LogStore as O0OO00O00OO00OOOO 
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFsI=O0OO00O00OO00OOOO.finished
import json as OOO000O00OOOOOOO0 
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFsz=OOO000O00OOOOOOO0.dumps
import sys as O000O00O0O0OO00OO 
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLszI=sys.modules
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFIz=O000O00O0O0OO00OO.argv
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFIs=O000O00O0O0OO00OO.exc_info
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLsFz=sys.path
rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzIs(O000O00O0O0OO00OO)
from JHOpen import JHOpen as OO0O000OOO00O0O0O 
def rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszFL(O0O0OOO0000OO00OO,OOOO000OOOOO000OO,O0OOOOO00O0000OOO,OO0OO000O00O00O0O):
 rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLIF=O0OO0O0O0OO0O0000()
 rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLIz=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsz('%Y%m%d',rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIFs(O0O0OOO0000OO00OO))
 rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLFI=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsz('%Y%m%d%H%M',rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIFs(O0O0OOO0000OO00OO))
 rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLFz=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIsz('%H%M',rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIFs(O0O0OOO0000OO00OO))
 rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLzI=OOOO000OOOOO000OO%{"yyyymmdd":rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLIz,"yyyymmddhhmm":rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLFI}
 rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLzF=O0OOOOO00O0000OOO%{"yyyymmdd":rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLIz,"hhmm":rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLFz}
 for rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsILF in OO0O000OOO00O0O0O().readLines(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLzI):
  if not rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsILF:
   continue 
  try:
   for rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsILz in rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLIF.transform(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsILF):
    rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsIFL=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsILz['jhd_datatype']
    rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsILz['jhd_userkey']=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsILz['jhd_userkey'].strip()
    rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsIFz=OO0OO000O00O00O0O%{"yyyymmdd":rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLIz,"hhmm":rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLFz,'datatype':rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsIFL}
    rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsIzL=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFsz(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsILz,ensure_ascii=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzIF)
    O0OO00O00OO00OOOO(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsIFz,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsIzL)
  except:
   import traceback as OOOOO0000000OO00O 
   rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsIzF,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFLI,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFLz=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFIs()
   rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFIL=OOOOO0000000OO00O.format_exception(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsIzF,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFLI,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFLz)
   rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFIL.append(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsILF)
   O0OO00O00OO00OOOO(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsLzF,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFsz(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzFs(lambda O0O00OO00OO0OO000:O0O00OO00OO0OO000.strip(),rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFIL)))
 rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFsI(iszip=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFzI)
if __name__=="__main__":
 if 'transform_ios'in rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFIz:
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFzL="/data/nginxlogs/jhsaaslogs_ios/access_jhlogs.%(yyyymmddhhmm)s"
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFzI="/data/transform/ios_log/err/%(yyyymmdd)s/%(hhmm)s.err"
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszLI="/data/transform/ios_log/%(datatype)s/%(yyyymmdd)s/%(hhmm)s.log"
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszLF=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzFI(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIFz()-60*5)
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszFL(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszLF,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFzL,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFzI,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszLI)
 if 'transform_android'in rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFIz:
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFzL="/data/nginxlogs/jhsaaslogs/access_jhlogs.%(yyyymmddhhmm)s"
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFzI="/data/transform/android_log/err/%(yyyymmdd)s/%(hhmm)s.err"
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszLI="/data/transform/android_log/%(datatype)s/%(yyyymmdd)s/%(hhmm)s.log"
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszLF=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLzFI(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIFz()-60*5)
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszFL(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszLF,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFzL,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmsFzI,rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszLI)
 if 'store'in rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLFIz:
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszIL=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIzs(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIzF('20160823+173700','%Y%m%d+%H%M%S'))
  rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszIF=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIzs(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmLIzF('20160823+180600','%Y%m%d+%H%M%S'))
  while rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszIL<=rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszIF:
   try:
    rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszFL(rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszIF,src_file_format="/data1/nginxlogs/jhsaaslogs/access_jhlogs.%(yyyymmddhhmm)s",errlog_path_format="/data1/logs/transformsaaslogs/err/%(yyyymmdd)s/%(hhmm)s.err",filename_format="/data1/logs/transformsaaslogs/%(datatype)s/%(yyyymmdd)s/%(hhmm)s.log")
   except:
    import traceback as O000OOO0O000OOOOO 
    print(O000OOO0O000OOOOO.print_exc())
   rhcbxltdPYyRgJeDXofijEKCnGvMONSBwTuUVaWkQqpAHmszIF-=60 
# Created by pyminifier (https://github.com/liftoff/pyminifier)

